Repository 42openproject/whatdidyoueat, pull requests merged in 2021-12, with the labels that each got.

#72 Fe/profile page infos
  client/db.json
  client/src/ProfilePageView/EditNickModal.js
  client/src/ProfilePageView/ProfilePage.js
  client/src/ProfilePageView/UserAcheivement.js
  client/src/ProfilePageView/UserFollow.js
  client/src/ProfilePageView/UserProfile.js
  client/src/ProfilePageView/UserTags.js
  client/src/stylesheets/NaviBar.css
  client/src/stylesheets/ProfilePage.css
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#73 Be/api/login/google
  server/routes/login.js
  server/services/login.js
  server/test.sh
Labels: :computer: 백엔드, :joystick: 기능

#79 #78 FEAT - google 로그인 시 google id, email 데이터베이스에 저장
  client/.env
  client/src/LoginPageView/LoginPage.js
  client/src/LoginPageView/SetNicknamePage.js
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#82 [2단계] 포스트 Upload 페이지 Title 추가 #80
  client/src/LoginPageView/SetNicknamePage.js
  client/src/PostPageView/PostPage.js
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#84 Fe/profile page tags
  client/db.json
  client/src/ProfilePageView/EditNickModal.js
  client/src/ProfilePageView/OnToggleTagModal.js
  client/src/ProfilePageView/TagList.js
  client/src/ProfilePageView/UserProfile.js
  client/src/ProfilePageView/UserTags.js
  client/src/stylesheets/ProfilePage.css
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#86 Be/api/posts/id
  .gitignore
  package-lock.json
  server/app.js
  server/config/config.json
  server/package-lock.json
  server/package.json
  server/routes/img.js
  server/routes/posts.js
  server/services/img.js
  server/services/posts.js
  server/test.sh
Labels: :computer: 백엔드, :joystick: 기능

#93 Fe/api update
  client/.eslintrc.json
  client/src/LoginPageView/LoginPage.js
  client/src/LoginPageView/SetNicknamePage.js
  client/src/MainPageView/MainCalendar.js
  client/src/MainPageView/MainFollow.js
  client/src/MainPageView/MainPage.js
  client/src/MainPageView/MainPost.js
  client/src/MainPageView/PostList.js
  client/src/MainPageView/PostTitle.js
  client/src/MainPageView/UserPage.js
  client/src/PostPageView/PostPage.js
  client/src/ProfilePageView/OnToggleTagModal.js
  client/src/ProfilePageView/ProfilePage.js
  client/src/ProfilePageView/UserProfile.js
  client/src/ProfilePageView/UserTags.js
  client/src/stylesheets/LoginPage.css
Labels: 🧑🏻‍💻 프론트엔드

#97 Be/api/get/title/id
  server/package.json
  server/services/posts.js
  server/services/titles.js
  server/test.sh
Labels: :computer: 백엔드

#98 Fe/search page template
  client/src/SearchPageView/SearchBar.js
  client/src/SearchPageView/SearchPage.js
  client/src/SearchPageView/SearchPost.js
  client/src/stylesheets/SearchPage.css
Labels: 🧑🏻‍💻 프론트엔드, 📱 UI

#102 Profile page image
  .gitignore
  client/.env
  client/src/LoginPageView/SetNicknamePage.js
  client/src/ProfilePageView/UserProfile.js
  client/src/ProfilePageView/UserProfileImage.js
  client/src/stylesheets/ProfilePage.css
  server/app.js
  server/models/images.js
  server/models/users.js
  server/package-lock.json
  server/package.json
  server/routes/img.js
  server/routes/users.js
  server/services/img.js
  server/services/multer.js
  server/services/users.js
  server/test/test.sh
Labels: 🧑🏻‍💻 프론트엔드, :computer: 백엔드, :joystick: 기능, ❕중요

#106 Fe/calendar api + get nickname api 요청 줄이기
  client/src/MainPageView/MainCalendar.js
  client/src/MainPageView/MainPage.js
  client/src/MainPageView/MainPost.js
  client/src/MainPageView/PostTitle.js
  client/src/ProfilePageView/ProfilePage.js
  client/src/ProfilePageView/UserProfile.js
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#107 Fe/user page
  client/src/MainPageView/MainPage.js
  client/src/MainPageView/PostTitle.js
  client/src/MainPageView/UserPage.js
  client/src/MainPageView/UserPostTitle.js
Labels: 🧑🏻‍💻 프론트엔드

#109 Be/users/id/tag
  server/models/tags.js
  server/models/users.js
  server/models/users_tag.js
  server/routes/users.js
  server/services/users.js
  server/test/test.sh
Labels: :computer: 백엔드, :joystick: 기능

#112 Fe/calendar
  client/db.json
  client/src/App.js
  client/src/Calendar/Calendar.css
  client/src/Calendar/Calendar.js
  client/src/Calendar/CalendarDateItem.js
  client/src/Calendar/Test.js
  client/src/MainPageView/MainCalendar.js
  client/src/MainPageView/MainPage.js
  client/src/MainPageView/PostTitle.js
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#113 Fe/search page all post
  client/db.json
  client/src/SearchPageView/SearchPost.js
  client/src/SearchPageView/TodayPostList.js
  client/src/stylesheets/SearchPage.css
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#114 Be/posts/id image
  server/models/images.js
  server/models/posts.js
  server/routes/posts.js
  server/services/posts.js
  server/services/users.js
Labels: :computer: 백엔드, :joystick: 기능

#115 Be/nickname/check/:id
  server/package-lock.json
  server/package.json
  server/routes/posts.js
  server/routes/users.js
  server/services/users.js
  server/test/data/nicknameCheck.json
  server/test/integration/product.test.js
  server/test/test.sh
  server/test/unit/product.test.js
Labels: :computer: 백엔드, :joystick: 기능

#119 Calendar GET response 수정, login/google POST isSigned
  server/config/config.json
  server/routes/login.js
  server/services/calendar.js
  server/services/login.js
  server/test/test.sh
Labels: :computer: 백엔드, :joystick: 기능

#121 Fe/post page
  client/src/MainPageView/MainPost.js
  client/src/MainPageView/PostList.js
  client/src/MainPageView/PostTitle.js
  client/src/PostPageView/ErrorModal.js
  client/src/PostPageView/ImageUploader.js
  client/src/PostPageView/PostPage.js
  client/src/SearchPageView/TodayPostList.js
  client/src/stylesheets/MainPage.css
  client/src/stylesheets/PostPage.css
  client/src/stylesheets/SearchPage.css
Labels: 🧑🏻‍💻 프론트엔드, 📱 UI, :joystick: 기능

#125 Fe/apis
  client/src/LoginPageView/SetNicknamePage.js
  client/src/MainPageView/MainCalendar.js
  client/src/ProfilePageView/EditNickModal.js
  client/src/ProfilePageView/ProfilePage.js
  client/src/ProfilePageView/TagList.js
  client/src/ProfilePageView/UserProfile.js
  client/src/ProfilePageView/UserTags.js
  client/src/stylesheets/SetNicknamePage.css
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능

#131 Fe/build test
  .github/workflows/front-build-test.yml
  .github/workflows/front-deploy.yml
  client/.env
  client/package-lock.json
  client/package.json
  client/src/LoginPageView/LoginPage.js
  client/src/MainPageView/MainCalendar.js
  client/src/PostPageView/ImageUploader.js
  server/config/config.json
Labels: 🧑🏻‍💻 프론트엔드

#132 FEAT #126 - deploy invalidate 수정
  .github/workflows/front-deploy.yml
Labels: ✔️ 테스트

#133 FEAT #126 - deploy python, awscli 설치 추가
  .github/workflows/front-deploy.yml
Labels: ✔️ 테스트

#142 FEAT - GET explore
  server/app.js
  server/config/config.json
  server/routes/explore.js
  server/services/explore.js
  server/services/utils.js
  server/test/test.sh
Labels: :computer: 백엔드, :joystick: 기능

#143 Fe/UI
  client/src/Calendar/Calendar.css
  client/src/PostPageView/ImageUploader.js
  client/src/PostPageView/PostPage.js
  client/src/asset/ddd.png
  client/src/asset/ddd@2x.png
  client/src/stylesheets/Header.css
  client/src/stylesheets/MainPage.css
  client/src/stylesheets/NaviBar.css
  client/src/stylesheets/PostPage.css
Labels: 🧑🏻‍💻 프론트엔드

#144 FIX #140 - nickname 수정
  server/services/users.js
  server/services/utils.js
  server/test/test.sh
Labels: :computer: 백엔드

#145 Fe/explore
  client/src/SearchPageView/SearchPost.js
  client/src/SearchPageView/TodayPostList.js
  client/src/stylesheets/SearchPage.css
Labels: 🧑🏻‍💻 프론트엔드, :joystick: 기능
